### ISSUE TITLE
RGB or BGR?

### ISSUE THREAD

**Issue by cswhjiang** [flyyufelix/DenseNet-Keras#18]
Hi, this is a nice work. And I have some questions about how to use the model.

What tool is used convert the caffe model? And what order should be used for testing, RGB or BGR. Thanks.

**Comment by flyyufelix** [comment]
BGR. You can refer to https://github.com/flyyufelix/DenseNet-Keras/blob/master/test_inference.py. OpenCV reads the image into BGR format

As to your other question on converting Caffe to Keras, you can refer to my blog post: https://flyyufelix.github.io/2017/03/23/caffe-to-keras.html

**Comment by cswhjiang** [comment]
Thanks!
